# Generated by Django 4.2 on 2024-05-09 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contacto',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='contactForm_uuid',
            new_name='contacto_uuid',
        ),
    ]
