# Generated by Django 4.2 on 2024-05-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_contactform_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.IntegerField(default=4000),
            preserve_default=False,
        ),
    ]
